#Ansible bastionhost
---
- hosts: localhost
  become: yes
  gather_facts: false

  vars:
    users:
      albert:
        name: albert
        state: present
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJtvr09fmDxKfJsDYD1AaTebckKjhh6hptLW5CdWAdU91vVCmswSa/Dsnz8hcAXLqEZCp4Pqpu2nYj3uvit1mhJ9qvT0HdeQXjBkO9Pa2yzDazl7OEpGE15LWqvDuUkyCu5wpoztiHevzLIpOYkJcpyQbZcBmhqKhLNZ0Pf9yAa4eKlldgq2y3iGaCvGd2xCIxgW+rbTcN4/WTpUi1lY7rGxGZsIFjVgxwSTcEQ1DTtJ2TnQjcbjYAs7hHv2kF77gVzTy0QY2U036W+YV5BdUKB3deX2kfjDAk3E9TV5YZ5ZZd7koi0T36orErx2ohc3IrmjdZ0xs8SenxnrL/10mmcF8bTUcIyAbei67x3VdQH/QtLdiMYtg4gwZUF2qw5JU6DfBbS6bjavFEnSNbwSJGrM/vSNrWM/vGCL9rC8a3QRDWu0L9YoaRBkS6cz2Nz1se9TIehMTSR6ZnfqzF2ckrA4fDSN7J2LvvNkS5WManNRypBx1PvnAPMhQnebAuVq8="
        shell: /bin/bash
        groups: sudo
        append: yes
      regi:
        name: regi
        state: present
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJrz87cracG6i+PtYBzrk145ePpcoVPD7zjHX9IuPtgt1lDNrcyCCzKkr5ZtEXEMxVA9tnRup1sADh4qOwnPEUb3HDTfM2+sOGxfaMGqnqjxw+oztDZaUljaZmqGy8RDzHmruP65PRfGvSdvzGNX9LP3fXTxKh3xRMPDEdIwxyEa8krLHD37leADzUIWo2V8cq1JI+jmEh6L8fcUuJz1BVWaw3XUbVNKHZNsnYQ04D3gBEx4GJdU15Yj91+WZSyBUp6orpA72OAVo+z+t257MNHrLtHZgszQqvFuiDEM+tiE8E3BaTSURFwF4L72a6mWq+QGPrXsaw3WqAou5s/+vaFtoHz6AeTgrddPtn4fRjhGOrNVAcHL0unmu3dT9gZ4WxmZ4zpghnNHTcJyAgTI+C5r1MvybphLi4tnliAiN3B4r067nj4N/f20lRSxQkreBTxoPGQYdpVV+PybiKUFcwRtVQz6wlQJHf9CaD8eATbr14eH0j367nEaPK+etuYFk="
        shell: /bin/bash
        groups: sudo
        append: yes
      testuser:
        name: testuser
        state: absent
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJrz87cracG6i+PtYBzrk145ePpcoVPD7zjHX9IuPtgt1lDNrcyCCzKkr5ZtEXEMxVA9tnRup1sADh4qOwnPEUb3HDTfM2+sOGxfaMGqnqjxw+oztDZaUljaZmqGy8RDzHmruP65PRfGvSdvzGNX9LP3fXTxKh3xRMPDEdIwxyEa8krLHD37leADzUIWo2V8cq1JI+jmEh6L8fcUuJz1BVWaw3XUbVNKHZNsnYQ04D3gBEx4GJdU15Yj91+WZSyBUp6orpA72OAVo+z+t257MNHrLtHZgszQqvFuiDEM+tiE8E3BaTSURFwF4L72a6mWq+QGPrXsaw3WqAou5s/+vaFtoHz6AeTgrddPtn4fRjhGOrNVAcHL0unmu3dT9gZ4WxmZ4zpghnNHTcJyAgTI+C5r1MvybphLi4tnliAiN3B4r067nj4N/f20lRSxQkreBTxoPGQYdpVV+PybiKUFcwRtVQz6wlQJHf9CaD8eATbr14eH0j367nEaPK+etuAFK="
        shell: /bin/bash
        groups: sudo
        append: yes

  tasks:
    - name: Create User
      ansible.builtin.user:
        name: "{{ item.value.name }}"
        state: "{{ item.value.state }}"
        shell: "{{ item.value.shell }}"
        groups: "{{ item.value.groups }}"
        append: "{{ item.value.append }}"
      loop: "{{ lookup('dict', users, wantlist=True) }}"

    - name: Deploy SSH Public Key
      authorized_key:
        user: "{{ item.value.name }}"
        state: "{{ item.value.state }}"
        key: "{{ item.value.key }}"
      loop: "{{ lookup('dict', users, wantlist=True) }}"

    - name: "Allow wheel users to sudo without a password"
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^%wheel"
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"
